name: Lint

on:
  push:
  workflow_dispatch:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install GO
        uses: actions/setup-go@v3
        with: 
          go-version: 1.21

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 3m --verbose

      - name: staticcheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          install-go : false
          version: "2023.1.6"
          min-go-version: "1.21.x"

      - name: gofmt
        uses: Jerome1337/gofmt-action@v1.0.5
        with:
          gofmt-flags: "-l -d"
       
